Disabling ebtables for now, causing conflict
Error:
:: iptables-nft and iptables are in conflict. Remove iptables? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)